src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <fields>
        <fullName>type__c</fullName>
        <description>This specifies which type of records will be updated.</description>
        <inlineHelpText>Choose the object type of the records you wish to update.</inlineHelpText>
        <label>SObject Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUWTestObject__c.object
<CustomObject>
    <description>We need an object that contains every field type for the unit tests.</description>
    <label>MUW Test Object</label>
    <nameField>
        <label>MUW Test Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Test Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConfigurationTestUtility.cls
// testing class to easily build configuration objects
public class ConfigurationTestUtility {

    // this provides pre-existing values
    public static Configuration__c buildConfiguration() {
    	return buildConfiguration('name', 'MUWTestObject__c');
    }

    // builds the configuration and sets the name and type
    public static Configuration__c buildConfiguration(String name, String theType) {
    	// build the configuration
    	Configuration__c conf = new Configuration__c();
    	// set the name
    	conf.name = name;
    	// set the type
    	conf.type__c = theType;
    	// return the configuration
    	return conf;
    }

}