src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUWTestObject__c.object
<CustomObject>
    <description>We need an object that contains every field type for the unit tests.</description>
    <label>MUW Test Object</label>
    <nameField>
        <label>MUW Test Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Test Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UpdateValue__c.object
<CustomObject>
    <description>This stores a particular value for an update value.  An update value contains:

* The field name to update.
* The value to set the field to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Update Values</relationshipLabel>
        <relationshipName>R00N60000001Zvl0EAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The field name of the field to update.</description>
        <inlineHelpText>Choose the name of the field you wish to update.</inlineHelpText>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Update Value</label>
    <nameField>
        <label>MUW Update Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Update Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateValueEditControllerTest.cls
@IsTest
private class UpdateValueEditControllerTest {

    static testMethod void testCreateValue() {
        // build a configuration and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;

        // we have to set the retURL param for our controller to work        
        PageReference myPage = Page.UpdateValueEdit;
        Test.setCurrentPage(myPage);
        ApexPages.currentPage().getParameters().put('retURL', '/' + conf.id);
        
        // build a filter value but don't insert it
        UpdateValue__c uv = new UpdateValue__c();
        ApexPages.StandardController stdCont = new ApexPages.StandardController(uv);
        UpdateValueEditController cont = new UpdateValueEditController(stdCont);
        System.assertEquals(uv.fieldname__c, cont.getName());
        
        // verify that the configuration's name is correct
        String configurationName = cont.getConfigurationName();
        System.assertEquals(conf.name, configurationName);
        
        cont.setName('newName');
        cont.save();
        UpdateValue__c newUv = (UpdateValue__c)cont.getRecord();
        System.assertEquals('newName', newUv.fieldname__c);
        System.assertEquals(conf.id, newUv.configuration__c);
    }
    
    static testMethod void testUpdateValue() {
        // build a configuration and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;

        // we have to set the retURL param for our controller to work        
        PageReference myPage = Page.UpdateValueEdit;
        Test.setCurrentPage(myPage);
        ApexPages.currentPage().getParameters().put('retURL', '/' + conf.id);
        
        // build a filter value and insert it
        UpdateValue__c uv = UpdateValueTestUtility.buildUpdateValue('newname', 'name', 'blah', conf.id);
        insert uv;
        ApexPages.StandardController stdCont = new ApexPages.StandardController(uv);
        UpdateValueEditController cont = new UpdateValueEditController(stdCont);
        System.assertEquals(uv.fieldname__c, cont.getName());
        
        // verify that the configuration's name is correct
        String configurationName = cont.getConfigurationName();
        System.assertEquals(conf.name, configurationName);
        
        cont.setName('newName');
        cont.save();
        UpdateValue__c newUv = (UpdateValue__c)cont.getRecord();
        System.assertEquals('newName', newUv.fieldname__c);
        System.assertEquals(conf.id, newUv.configuration__c);
    }
    
    static testMethod void testGetUpdateableFields() {
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration('conf name', 'MUWTestObject__c');
        insert conf;
        UpdateValue__c uv = new UpdateValue__c();
        uv.configuration__c = conf.id;
        
        // we have to set the retURL param for our controller to work        
        PageReference myPage = Page.UpdateValueEdit;
        Test.setCurrentPage(myPage);
        ApexPages.currentPage().getParameters().put('retURL', '/' + conf.id);
        
        ApexPages.StandardController stdCont = new ApexPages.StandardController(uv);
        UpdateValueEditController cont = new UpdateValueEditController(stdCont);
        List<SelectOption> updateableFields = cont.getUpdateableFields();
    }

}