src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FilterValue__c.object
<CustomObject>
    <description>This stores a particular filter value for a configuration.  A filter value contains:

* The name of the field to filter on.
* The type of filter to apply.
* The value to compare the field&apos;s stored value to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Filter Values</relationshipLabel>
        <relationshipName>R00N60000001ZvklEAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FilterValue__c</fullName>
        <description>The value to which the field value should be compared.</description>
        <inlineHelpText>Choose the value to which the field value will be compared.</inlineHelpText>
        <label>Filter Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>MUW Filter Value</label>
    <nameField>
        <label>MUW Filter Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Filter Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUWTestObject__c.object
<CustomObject>
    <description>We need an object that contains every field type for the unit tests.</description>
    <label>MUW Test Object</label>
    <nameField>
        <label>MUW Test Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Test Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UpdateValue__c.object
<CustomObject>
    <description>This stores a particular value for an update value.  An update value contains:

* The field name to update.
* The value to set the field to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Update Values</relationshipLabel>
        <relationshipName>R00N60000001Zvl0EAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MUW Update Value</label>
    <nameField>
        <label>MUW Update Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Update Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConfigurationRunResultsControllerTest.cls
// this has the tests for the configuration run results controller
@IsTest
private class ConfigurationRunResultsControllerTest {
	
	static testMethod void testNoFilterValues() {
		// set the test's current page to the run results page
        PageReference myPage = Page.ConfigurationRunResults;
        Test.setCurrentPage(myPage);
            
        // build the configuration object and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;
        // instantiate the standard controller based on the configuration
        ApexPages.StandardController stdCont = new ApexPages.StandardController(conf);
        // instantiate the custom controller extension based on the standard controller
        ConfigurationRunResultsController cont = new ConfigurationRunResultsController(stdCont);
        
        // verify the update message when no filter values are added
        System.assertEquals(Constants.runResultsNoFilterValuesErrorMessage, cont.getUpdateMessage());
	}
	
	static testMethod void testNoUpdateValues() {
		// set the test's current page to the run results page
        PageReference myPage = Page.ConfigurationRunResults;
        Test.setCurrentPage(myPage);
            
        // build the configuration object and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;
        // instantiate the standard controller based on the configuration
        ApexPages.StandardController stdCont = new ApexPages.StandardController(conf);
        // instantiate the custom controller extension based on the standard controller
        ConfigurationRunResultsController cont = new ConfigurationRunResultsController(stdCont);
        
        // build and insert a filter value for the configuration
        FilterValue__c fv = FilterValueTestUtility.buildFilterValue('fv1', 'name', '=', 'barf', conf.id);
        insert fv;
        // verify the update message when no update values are added
        cont.doUpdate();
        System.assertEquals(Constants.runResultsNoUpdateValuesErrorMessage, cont.getUpdateMessage());
	}
	
	static testMethod void testNoMatchingRecordsUpdated() {
		// set the test's current page to the run results page
        PageReference myPage = Page.ConfigurationRunResults;
        Test.setCurrentPage(myPage);
            
        // build the configuration object and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;
        
        // build and insert a filter value for the configuration
        FilterValue__c fv = FilterValueTestUtility.buildFilterValue('fv1', 'name', '=', 'barf', conf.id);
        insert fv;
        
        // instantiate the standard controller based on the configuration
        ApexPages.StandardController stdCont = new ApexPages.StandardController(conf);
        // instantiate the custom controller extension based on the standard controller
        ConfigurationRunResultsController cont = new ConfigurationRunResultsController(stdCont);
        
        // now add an update value and check that no records are updated when the filter criteria
        // match no records
        UpdateValue__c uv = UpdateValueTestUtility.buildUpdateValue('uv1', 'name', 'newbarf', conf.id);
        insert uv;
        cont.doUpdate();
        System.assertEquals(Constants.noValuesUpdatedMessage, cont.getUpdateMessage());
	}
	
	// let's test the main method
	static testMethod void testMatchingRecordsUpdated() {
		// set the test's current page to the run results page
        PageReference myPage = Page.ConfigurationRunResults;
        Test.setCurrentPage(myPage);
        
        // build the configuration object and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;
        
        // build and insert a filter value for the configuration
        FilterValue__c fv = FilterValueTestUtility.buildFilterValue('fv1', 'name', '=', 'barf', conf.id);
        insert fv;
        
        // now add an update value and check that no records are updated when the filter criteria
        // match no records
        UpdateValue__c uv = UpdateValueTestUtility.buildUpdateValue('uv1', 'name', 'newbarf', conf.id);
        insert uv;
        
        // now add a matching test object
        MUWTestObject__c a = new MUWTestObject__c(name='barf');
        insert a;
        
        // instantiate the standard controller based on the configuration
        ApexPages.StandardController stdCont = new ApexPages.StandardController(conf);
        // instantiate the custom controller extension based on the standard controller
        ConfigurationRunResultsController cont = new ConfigurationRunResultsController(stdCont);
        
        // verify that it found the one test object
        System.assertEquals('Found 1 matching record(s)!', cont.getRecordCountMessage());
        
        // do the update
        cont.doUpdate();
        // verify that the page's update message is correct
        System.assertEquals(Constants.getSuccessfulUpdateMessage(1), cont.getUpdateMessage());
        // verify that the record was actually updated
        MUWTestObject__c newA = [select name from MUWTestObject__c where id=:a.id];
        System.assertEquals('newbarf', newA.name);
	}

}