src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SelectValue__c.object
<CustomObject>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Select Values</relationshipLabel>
        <relationshipName>R00N80000002yLkfEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Select Value</label>
    <nameField>
        <label>MUW Select Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Select Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SelectValueTestUtility.cls
public class SelectValueTestUtility {

    public static SelectValue__c buildSelectValue(String configurationId) {
        return buildSelectValue('sv name', 'name', configurationId);
    }

    public static SelectValue__c buildSelectValue(String name,
                                                  String fieldName,
                                                  String configurationId) {
        SelectValue__c sv = new SelectValue__c();
        sv.name = name;
        sv.fieldName__c = fieldName;
        sv.configuration__c = configurationId;
        return sv;
    }

}