src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <fields>
        <fullName>type__c</fullName>
        <description>This specifies which type of records will be updated.</description>
        <inlineHelpText>Choose the object type of the records you wish to update.</inlineHelpText>
        <label>SObject Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FilterValue__c.object
<CustomObject>
    <description>This stores a particular filter value for a configuration.  A filter value contains:

* The name of the field to filter on.
* The type of filter to apply.
* The value to compare the field&apos;s stored value to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Filter Values</relationshipLabel>
        <relationshipName>R00N60000001ZvklEAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The field name of the field to filter on.</description>
        <inlineHelpText>Choose the name of the field you wish to filter on.</inlineHelpText>
        <label>Field Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterValue__c</fullName>
        <description>The value to which the field value should be compared.</description>
        <inlineHelpText>Choose the value to which the field value will be compared.</inlineHelpText>
        <label>Filter Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>This controls the way the field values are compared to the specified values.  For example, the filter can check that the field value is or is not equal to the specified value.</description>
        <inlineHelpText>Choose the way you wish to compare the field value to the specified value.</inlineHelpText>
        <label>Operator</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Filter Value</label>
    <nameField>
        <label>MUW Filter Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Filter Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FilterValueEditController.cls
// this is the controller for the filter value edit page
public class FilterValueEditController extends BaseValueEditController {

    // keeps track of the field name
    private String name;
    // keeps track of the operator
    private String operator;

    // constructor for the custom controller extension
    public FilterValueEditController(ApexPages.StandardController stdController) {
        // set the controller
        this.stdController = stdController;
        this.objectType = 'FilterValue';
        // use a list because the query can return 0 or 1 record
        List<FilterValue__c> fv = [select id, fieldname__c, operator__c from filtervalue__c where id=:stdController.getId()];
        if(fv.size() == 1) {
            name = fv[0].fieldname__c;
            operator = fv[0].operator__c;
        }
    }
        
    // save the actual filter value
    public override PageReference save() {
        FilterValue__c fv = (FilterValue__c)stdController.getRecord();
        fv.fieldname__c = name;
        fv.operator__c = operator;
        // only need to set the configuration id if it hasn't already been set because it's a MD relationship
        // so you can't change it once it's set
        if(fv.configuration__c == null) {
           fv.configuration__c = getConfigurationId();
        }
        return stdController.save();
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    
    // get all filterable fields
    public List<SelectOption> getFilterableFields() {
        String confId = getConfigurationId();
        Configuration__c c = [select type__c from configuration__c where id=:confId];
        Map<String, Schema.SObjectField> fieldsMap = Schema.getGlobalDescribe().get(c.type__c).getDescribe().fields.getMap();
        Map<String, Map<String, Schema.SObjectField>> parentFieldsMap = DescribeUtility.getParentFieldDescribeMaps(fieldsMap);
        return SelectOptionGenerator.getFields(c.type__c, false, true, true, false, false,
               fieldsMap, parentFieldsMap);
    }
    
    // get the operators
    public List<SelectOption> getOperators() {
        return SelectOptionGenerator.getOperators(null, null); 
    }
    
}