src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <fields>
        <fullName>type__c</fullName>
        <description>This specifies which type of records will be updated.</description>
        <inlineHelpText>Choose the object type of the records you wish to update.</inlineHelpText>
        <label>SObject Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UpdateValue__c.object
<CustomObject>
    <description>This stores a particular value for an update value.  An update value contains:

* The field name to update.
* The value to set the field to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Update Values</relationshipLabel>
        <relationshipName>R00N60000001Zvl0EAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The field name of the field to update.</description>
        <inlineHelpText>Choose the name of the field you wish to update.</inlineHelpText>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Update Value</label>
    <nameField>
        <label>MUW Update Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Update Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateValueEditController.cls
public class UpdateValueEditController extends BaseValueEditController {

    private String name;

    public UpdateValueEditController(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        this.objectType = 'UpdateValue';
        List<UpdateValue__c> uv = [select id, fieldname__c from updatevalue__c where id=:stdController.getId()];
        if(uv.size() == 1) {
            name = uv[0].fieldname__c;
        }
    }
        
    public override PageReference save() {
        UpdateValue__c uv = (UpdateValue__c)stdController.getRecord();
        uv.fieldname__c = name;
        if(uv.configuration__c == null) {
            uv.configuration__c = getConfigurationId();
        }
        return stdController.save();
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public List<SelectOption> getUpdateableFields() {
        String confId = getConfigurationId();
        Configuration__c c = [select type__c from configuration__c where id=:confId];
        return SelectOptionGenerator.getFields(c.type__c, false, false, false, true, true,
               Schema.getGlobalDescribe().get(c.type__c).getDescribe().fields.getMap(), null);
    }
    
}