src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FilterValue__c.object
<CustomObject>
    <description>This stores a particular filter value for a configuration.  A filter value contains:

* The name of the field to filter on.
* The type of filter to apply.
* The value to compare the field&apos;s stored value to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Filter Values</relationshipLabel>
        <relationshipName>R00N60000001ZvklEAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The field name of the field to filter on.</description>
        <inlineHelpText>Choose the name of the field you wish to filter on.</inlineHelpText>
        <label>Field Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterValue__c</fullName>
        <description>The value to which the field value should be compared.</description>
        <inlineHelpText>Choose the value to which the field value will be compared.</inlineHelpText>
        <label>Filter Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>This controls the way the field values are compared to the specified values.  For example, the filter can check that the field value is or is not equal to the specified value.</description>
        <inlineHelpText>Choose the way you wish to compare the field value to the specified value.</inlineHelpText>
        <label>Operator</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Filter Value</label>
    <nameField>
        <label>MUW Filter Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Filter Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FilterValueEditControllerTest.cls
// tests the controller for the filter value edit page
@IsTest
private class FilterValueEditControllerTest {

    static testMethod void testCreateValue() {
        // build a configuration and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;

        // we have to set the retURL param for our controller to work        
        PageReference myPage = Page.FilterValueEdit;
        Test.setCurrentPage(myPage);
        ApexPages.currentPage().getParameters().put('retURL', '/' + conf.id);
        
        // build a filter value but don't insert it
        FilterValue__c fv = new FilterValue__c();
        ApexPages.StandardController stdCont = new ApexPages.StandardController(fv);
        FilterValueEditController cont = new FilterValueEditController(stdCont);
        System.assertEquals(fv.fieldname__c, cont.getName());
        System.assertEquals(fv.operator__c, cont.getOperator());
        
        // verify that the configuration's name is correct
        String configurationName = cont.getConfigurationName();
        System.assertEquals(conf.name, configurationName);
        
        cont.setName('newName');
        cont.setOperator('newOp');
        cont.save();
        FilterValue__c newFv = (FilterValue__c)cont.getRecord();
        System.assertEquals('newName', newFv.fieldname__c);
        System.assertEquals('newOp', newFv.operator__c);
        System.assertEquals(conf.id, newFv.configuration__c);
    }

    static testMethod void testUpdateValue() {
        // build a configuration and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;
        // build a filter value and insert it with the previously created conf
        // as its parent
        FilterValue__c fv = FilterValueTestUtility.buildFilterValue(conf.id);
        insert fv;
        ApexPages.StandardController stdCont = new ApexPages.StandardController(fv);
        FilterValueEditController cont = new FilterValueEditController(stdCont);
        System.assertEquals(fv.fieldname__c, cont.getName());
        System.assertEquals(fv.operator__c, cont.getOperator());
        
        // verify that the configuration's name is correct
        String configurationName = cont.getConfigurationName();
        System.assertEquals(conf.name, configurationName);
        
        cont.setName('newName');
        cont.setOperator('newOp');
        cont.save();
        FilterValue__c newFv = (FilterValue__c)cont.getRecord();
        System.assertEquals('newName', newFv.fieldname__c);
        System.assertEquals('newOp', newFv.operator__c);
    }
    
    static testMethod void testGetterAndSetter() {
        FilterValue__c fv = new FilterValue__c();
        ApexPages.StandardController stdCont = new ApexPages.StandardController(fv);
        FilterValueEditController cont = new FilterValueEditController(stdCont);
        cont.setName('name');
        cont.setOperator('op');
        System.assertEquals('name', cont.getName());
        System.assertEquals('op', cont.getOperator());
    }

    static testMethod void testGetFilterableFields() {
        // build a configuration and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration();
        insert conf;
        // build a filter value and insert it with the previously created conf
        // as its parent
        FilterValue__c fv = FilterValueTestUtility.buildFilterValue(conf.id);
        insert fv;
        ApexPages.StandardController stdCont = new ApexPages.StandardController(fv);
        FilterValueEditController cont = new FilterValueEditController(stdCont);
        List<SelectOption> filterableFields = cont.getFilterableFields();
        System.assert(filterableFields != null);
    }
    
    static testMethod void testGetOperators() {
        FilterValue__c fv = new FilterValue__c();
        ApexPages.StandardController stdCont = new ApexPages.StandardController(fv);
        FilterValueEditController cont = new FilterValueEditController(stdCont);
        List<SelectOption> operators = cont.getOperators();
        System.assert(operators != null);
    }

}