src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <fields>
        <fullName>type__c</fullName>
        <description>This specifies which type of records will be updated.</description>
        <inlineHelpText>Choose the object type of the records you wish to update.</inlineHelpText>
        <label>SObject Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUWTestObject__c.object
<CustomObject>
    <description>We need an object that contains every field type for the unit tests.</description>
    <label>MUW Test Object</label>
    <nameField>
        <label>MUW Test Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Test Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConfigurationEditControllerTest.cls
// this tests the configuration edit page's controller
@IsTest
private class ConfigurationEditControllerTest {

    static testMethod void testConstructorAndSave() {
        // setup the page and set it as the test's current page
        PageReference myPage = Page.ConfigurationEdit;
        Test.setCurrentPage(myPage);

        // first instantiate the configuration object and insert it
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration('theName', 'MUWTestObject__c');
        insert conf;
        // create the custom extension based on that standard controller
        ConfigurationEditController cont = getController(conf);
        // set the type to something
        cont.setTheType(Constants.none);
        cont.save();
        // verify that the record's been updated by the save operation (but not to the DB)
        Configuration__c newConf = cont.getRecord();
        System.assertEquals(Constants.none, newConf.type__c);
        // query for that configuration
        newConf = [select id, name, type__c from configuration__c where id=:conf.id];
        System.assertEquals('MUWTestObject__c', newConf.type__c);
    }
    
    static testMethod void testGetterAndSetter() {
        // get the controller
        ConfigurationEditController cont = getController();
        // set the type
        cont.setTheType('blah');
        // assert that it's been set
        System.assertEquals('blah', cont.getTheType());
    }
    
    static testMethod void testGetSupportedTypes() {
        // get the controller
        ConfigurationEditController cont = getController();
        // get the supported types
        List<SelectOption> supportedTypes = cont.getSupportedTypes();
        // check that the list isn't null
        System.assert(supportedTypes != null);
        // check that the list has more than 1 option
        System.assert(supportedTypes.size() > 1);
    }
    
    // another util to get the controller
    private static ConfigurationEditController getController() {
        // instantiate a dummy configuration to use when creating the standard controller
        Configuration__c conf = new Configuration__c();
        // pass it to the controller
        return getController(conf);
    }
    
    // simple test utility to get the controller
    private static ConfigurationEditController getController(Configuration__c conf) {
        // create the standard controller for the passed in object
        ApexPages.StandardController stdCont = new ApexPages.StandardController(conf);
        // create the custom extension based on that standard controller
        ConfigurationEditController cont = new ConfigurationEditController(stdCont);
        // return it
        return cont;
    }

}