src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <fields>
        <fullName>type__c</fullName>
        <description>This specifies which type of records will be updated.</description>
        <inlineHelpText>Choose the object type of the records you wish to update.</inlineHelpText>
        <label>SObject Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FilterValue__c.object
<CustomObject>
    <description>This stores a particular filter value for a configuration.  A filter value contains:

* The name of the field to filter on.
* The type of filter to apply.
* The value to compare the field&apos;s stored value to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Filter Values</relationshipLabel>
        <relationshipName>R00N60000001ZvklEAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The field name of the field to filter on.</description>
        <inlineHelpText>Choose the name of the field you wish to filter on.</inlineHelpText>
        <label>Field Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterValue__c</fullName>
        <description>The value to which the field value should be compared.</description>
        <inlineHelpText>Choose the value to which the field value will be compared.</inlineHelpText>
        <label>Filter Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LogicalJoin__c</fullName>
        <description>The logical join that will be used to join this filter value with the next filter value (if it exists).</description>
        <inlineHelpText>Choose how this filter value will be logically joined with the next filter value (if it exists).  The order of filter values is determined by the names of the filter value records (alphabetically).</inlineHelpText>
        <label>Logical Join</label>
        <picklist>
            <picklistValues>
                <fullName>AND</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>This controls the way the field values are compared to the specified values.  For example, the filter can check that the field value is or is not equal to the specified value.</description>
        <inlineHelpText>Choose the way you wish to compare the field value to the specified value.</inlineHelpText>
        <label>Operator</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Filter Value</label>
    <nameField>
        <label>MUW Filter Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Filter Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SelectValue__c.object
<CustomObject>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Select Values</relationshipLabel>
        <relationshipName>R00N80000002yLkfEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Select Value</label>
    <nameField>
        <label>MUW Select Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Select Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UpdateValue__c.object
<CustomObject>
    <description>This stores a particular value for an update value.  An update value contains:

* The field name to update.
* The value to set the field to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Update Values</relationshipLabel>
        <relationshipName>R00N60000001Zvl0EAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The field name of the field to update.</description>
        <inlineHelpText>Choose the name of the field you wish to update.</inlineHelpText>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldValue__c</fullName>
        <description>The value to set the selected field to.</description>
        <inlineHelpText>Choose the value to set the selected field to.</inlineHelpText>
        <label>FIeld Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>MUW Update Value</label>
    <nameField>
        <label>MUW Update Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Update Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConfigurationRunResultsController.cls
// this is the controller for the page that lets you run a saved configuration
public with sharing class ConfigurationRunResultsController {
	
	// this keeps track of the standard controller that the custom controller extensions use
	private ApexPages.StandardController stdController;
	// stores the message to report back to the user
	private String updateMessage;
	// stores the number of records this would find
	private String recordCountMessage;
	
	// controller is a custom extension
	public ConfigurationRunResultsController(ApexPages.StandardController stdController) {
		this.stdController = stdController;
		
		// store the configuration
		Configuration__c conf = getConfiguration();
		// figure out how many SelectValues exist on this config
		Integer selectValueCount = [select count() from SelectValue__c where configuration__c=:conf.id];
		// construct the query utility based on the selected type, the filter values, and the fields map
		QueryUtility queryUtil = getQueryUtility(conf, true);
		if(queryUtil == null) {
			this.updateMessage = Constants.runResultsNoFilterValuesErrorMessage;
		} else {
	        try {
	            Integer recordCount = queryUtil.getNumberOfRecords();
	            // set the appropriate update message based on the number of updated records
	            if(recordCount == 10000) {
	                recordCountMessage = Constants.tooManyMatchingRecordsErrorMessage;
	            } else if(recordCount == 0) {
	                recordCountMessage = Constants.noValuesUpdatedMessage;
	            } else {
	                // if the user didn't select and fields to display, let's just show how many match
	                if(selectValueCount == 0) {
	                    recordCountMessage = 'Found ' + recordCount + ' matching record(s)!';
	                // if there are too many matching records we can't show them all
	                } else if(recordCount > 500) {
	                    recordCountMessage = 'There are too many matching records to display detailed information on all of them. Found ' 
	                      + recordCount + ' matching record(s)! Are you certain you want to update all of them?';
	                // otherwise show all the matching records in a table 
	                } else {
	                    recordCountMessage = queryUtil.getTableHtml();
	                }
	            }
	        } catch(System.QueryException e) {
	            updateMessage = Constants.getUnknownQueryProblemErrorMessage(e.getMessage());
	        }
		}
	}
	
	private Configuration__c getConfiguration() {
		// grab the configuration object with a query
		return [select id, type__c from configuration__c where id=:stdController.getId()];
	}
	
	private QueryUtility getQueryUtility(Configuration__c conf, boolean doSelect) {
		// store the selected type in a variable
		String selectedType = conf.type__c;
		// get the map that goes from string -> sobjectfield based on the chosen type
		Map<String, Schema.SObjectField> fieldsMap = Schema.getGlobalDescribe().get(selectedType).getDescribe().fields.getMap();
		// also get the fields map for all supported parent sobject types
		Map<String, Map<String, Schema.SObjectField>> parentFieldsMap = DescribeUtility.getParentFieldDescribeMaps(fieldsMap);
		// build a list of filter values
		List<FilterValue> filterValues = new List<FilterValue>();
		// build a list of select values
		List<String> selectValues = null;
		if(doSelect) {
			selectValues = new List<String>();
			// iterate over all the configuration's select values and add them to the list
			for(SelectValue__c sv : [select id, fieldname__c from selectvalue__c where configuration__c=:conf.id]) {
				selectValues.add(sv.fieldname__c);
			}
		}
		// iterate over all the configuration's filter values and add them to the list
		for(FilterValue__c fv : [select id, fieldname__c, operator__c, filtervalue__c, logicaljoin__c from filtervalue__c where configuration__c=:conf.id order by name]) {
			filterValues = FilterValue.addFilterValueToList(fv.fieldname__c, fv.operator__c, fv.filtervalue__c, fv.logicaljoin__c, filterValues);
		}
		// if the list is empty, then we can't do anything, so set the error message and return
		if(filterValues.size() == 0) {
			updateMessage = Constants.runResultsNoFilterValuesErrorMessage;
			return null;
		}
		// construct the query utility based on the selected type, the filter values, and the fields map
		return new QueryUtility(selectValues, selectedType, filterValues, fieldsMap, parentFieldsMap);
	}
	
	// this action does the updates
	public PageReference doUpdate() {
		// grab the configuration object with a query
		Configuration__c conf = getConfiguration();
		// store the selected type in a variable
		String selectedType = conf.type__c;
		// construct the query utility based on the selected type, the filter values, and the fields map
		QueryUtility queryUtil = getQueryUtility(conf, false);
		// build a list of update values
		List<UpdateValue> updateValues = new List<UpdateValue>();
		// iterate over all the configuration's update values and add them to the list
		for(UpdateValue__c uv : [select id, fieldname__c, fieldvalue__c from updatevalue__c where configuration__c=:conf.Id]) {
			updateValues = UpdateValue.addUpdateValueToList(uv.fieldname__c, uv.fieldvalue__c, updateValues);
		}
		// if the list is empty, then we can't do anything, so set the error message and return
		if(updateValues.size() == 0) {
			updateMessage = Constants.runResultsNoUpdateValuesErrorMessage;
			return null;
		}
		// get the map that goes from string -> sobjectfield based on the chosen type
		Map<String, Schema.SObjectField> fieldsMap = Schema.getGlobalDescribe().get(selectedType).getDescribe().fields.getMap();
		// construct the update utility based on the query utility, update values, and the fields map
		UpdateUtility updateUtil = new UpdateUtility(queryUtil, updateValues, fieldsMap);
		// do the update!
		integer recordCount = updateUtil.updateRecords();
		if(recordCount == 0) {
			// no records were found :(
            updateMessage = Constants.noValuesUpdatedMessage; 
		} else if(recordCount > 10000) {
			// too many records were found! :(
			updateMessage = Constants.tooManyMatchingRecordsErrorMessage;
		} else {
			// awesome, we did the update, here are how many you updated
            updateMessage = Constants.getSuccessfulUpdateMessage(recordCount);
		}
		// return nothing - we don't want a redirect
		return null;
	}
	
	// used by the apex page to get the update message
	public String getUpdateMessage() {
		return this.updateMessage;
	}
	
	public String getRecordCountMessage() {
		return this.recordCountMessage;
	}
	
}