src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <fields>
        <fullName>type__c</fullName>
        <description>This specifies which type of records will be updated.</description>
        <inlineHelpText>Choose the object type of the records you wish to update.</inlineHelpText>
        <label>SObject Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUWTestObject__c.object
<CustomObject>
    <description>We need an object that contains every field type for the unit tests.</description>
    <label>MUW Test Object</label>
    <nameField>
        <label>MUW Test Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Test Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SelectValue__c.object
<CustomObject>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Select Values</relationshipLabel>
        <relationshipName>R00N80000002yLkfEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MUW Select Value</label>
    <nameField>
        <label>MUW Select Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Select Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SelectValueTriggerTest.cls
@IsTest
private class SelectValueTriggerTest {

    static testMethod void testOneLessThanTooMany() {
        // set up a configuration
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration('conf', 'MUWTestObject__c');
        insert conf;
        // set up another configuration
        Configuration__c conf2 = ConfigurationTestUtility.buildConfiguration('conf2', 'MUWTestObject__c');
        insert conf2;
        
        // insert 49 select values on both
        List<SelectValue__c> svs = new List<SelectValue__c>();
        for(integer i=0; i<49; i++) {
            SelectValue__c sv = SelectValueTestUtility.buildSelectValue('name' + i, 'name', conf.id);
            SelectValue__c sv2 = SelectValueTestUtility.buildSelectValue('name' + i, 'name', conf2.id);
            svs.add(sv);
            svs.add(sv2);
        }
        insert svs;
        
        // insert five more for the first one and only one more for the second
        svs = new List<SelectValue__c>();
        for(integer i=0; i<5; i++) {
            SelectValue__c sv = SelectValueTestUtility.buildSelectValue('newname', 'name', conf.id);
            svs.add(sv);
        }
        svs.add(SelectValueTestUtility.buildSelectValue('newname2', 'name', conf2.id));
        try {
            insert svs;
            // shouldn't get here
            System.assert(false, 'exception should have been thrown!');
        } catch(System.DmlException e) {
            for(integer i=0; i<e.getNumDml(); i++) {
                System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(i));
                System.assertEquals(Constants.tooManyFilterValuesErrorMessage, e.getDmlMessage(i));
            }
        }
        // verify that the select value added to the second configuration is rolled back even though
        // it was fine.
        integer count = [select count() from SelectValue__c where configuration__c=:conf2.id];
        System.assertEquals(49, count);
    }

    static testMethod void testTooMany() {
        // set up a configuration
        Configuration__c conf = new Configuration__c();
        conf.name = 'tooManyTest';
        conf.type__c = 'MUWTestObject__c';
        insert conf;
        
        // insert 50 filter values
        List<SelectValue__c> svs = new List<SelectValue__c>();
        for(integer i=0; i<50; i++) {
            SelectValue__c sv = SelectValueTestUtility.buildSelectValue('name' + i, 'name', conf.id);
            svs.add(sv);
        }
        insert svs;
        
        // insert one more, should fail
        SelectValue__c sv = SelectValueTestUtility.buildSelectValue('newname', 'name', conf.id);
        try {
            insert sv;
            // shouldn't get here
            System.assert(false, 'exception should have been thrown!');
        } catch(System.DmlException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(0));
            System.assertEquals(Constants.tooManyFilterValuesErrorMessage, e.getDmlMessage(0));
        }
    }
    
    static testMethod void testFieldValidations() {
        // set up a configuration
        Configuration__c conf = new Configuration__c();
        conf.name = 'testFieldValidations';
        conf.type__c = 'MUWTestObject__c';
        insert conf;
        
        // set fieldname to --none--
        SelectValue__c sv = SelectValueTestUtility.buildSelectValue('nofieldname', Constants.none, conf.id);
        try {
            insert sv;
            // shouldn't get here
            System.assert(false, 'exception should have been thrown');
        } catch(System.DmlException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(0));
            System.assertEquals(Constants.filterValueIncorrectFieldNameErrorMessage, e.getDmlMessage(0));
        }
    }

}