src/objects/Configuration__c.object
<CustomObject>
    <description>This is the parent object for storing a particular mass update operator that a user wants to perform repeatedly.</description>
    <fields>
        <fullName>type__c</fullName>
        <description>This specifies which type of records will be updated.</description>
        <inlineHelpText>Choose the object type of the records you wish to update.</inlineHelpText>
        <label>SObject Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MUW Configuration</label>
    <nameField>
        <label>MUW Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FilterValue__c.object
<CustomObject>
    <description>This stores a particular filter value for a configuration.  A filter value contains:

* The name of the field to filter on.
* The type of filter to apply.
* The value to compare the field&apos;s stored value to.</description>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>MUW Configuration</label>
        <referenceTo>Configuration__c</referenceTo>
        <relationshipLabel>MUW Filter Values</relationshipLabel>
        <relationshipName>R00N60000001ZvklEAC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FilterValue__c</fullName>
        <description>The value to which the field value should be compared.</description>
        <inlineHelpText>Choose the value to which the field value will be compared.</inlineHelpText>
        <label>Filter Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>MUW Filter Value</label>
    <nameField>
        <label>MUW Filter Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Filter Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUWTestObject__c.object
<CustomObject>
    <description>We need an object that contains every field type for the unit tests.</description>
    <label>MUW Test Object</label>
    <nameField>
        <label>MUW Test Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MUW Test Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FilterValueTriggerTest.cls
@IsTest
private class FilterValueTriggerTest {
	
	static testMethod void testOneLessThanTooMany() {
		// set up a configuration
        Configuration__c conf = ConfigurationTestUtility.buildConfiguration('conf', 'MUWTestObject__c');
        insert conf;
        // set up another configuration
        Configuration__c conf2 = ConfigurationTestUtility.buildConfiguration('conf2', 'MUWTestObject__c');
        insert conf2;
        
        // insert 49 filter values on both
        List<FilterValue__c> fvs = new List<FilterValue__c>();
        for(integer i=0; i<49; i++) {
            FilterValue__c fv = FilterValueTestUtility.buildFilterValue('name' + i, 'name', '=', 'blah', conf.id);
            FilterValue__c fv2 = FilterValueTestUtility.buildFilterValue('name' + i, 'name', '=', 'blah', conf2.id);
            fvs.add(fv);
            fvs.add(fv2);
        }
        insert fvs;
        
        // insert five more for the first one and only one more for the second
        fvs = new List<FilterValue__c>();
        for(integer i=0; i<5; i++) {
            FilterValue__c fv = FilterValueTestUtility.buildFilterValue('newname', 'name', '=', 'blah', conf.id);
            fvs.add(fv);
        }
        fvs.add(FilterValueTestUtility.buildFilterValue('newname2', 'name', '=', 'blah', conf2.id));
        try {
            insert fvs;
            // shouldn't get here
            System.assert(false, 'exception should have been thrown!');
        } catch(System.DmlException e) {
        	for(integer i=0; i<e.getNumDml(); i++) {
                System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(i));
                System.assertEquals(Constants.tooManyFilterValuesErrorMessage, e.getDmlMessage(i));
        	}
        }
        // verify that the filter value added to the second configuration is rolled back even though
        // it was fine.
        integer count = [select count() from filtervalue__c where configuration__c=:conf2.id];
        System.assertEquals(49, count);
	}

    static testMethod void testTooMany() {
    	// set up a configuration
    	Configuration__c conf = new Configuration__c();
    	conf.name = 'tooManyTest';
    	conf.type__c = 'MUWTestObject__c';
    	insert conf;
    	
    	// insert 50 filter values
    	List<FilterValue__c> fvs = new List<FilterValue__c>();
    	for(integer i=0; i<50; i++) {
    		FilterValue__c fv = FilterValueTestUtility.buildFilterValue('name' + i, 'name', '=', 'blah', conf.id);
    		fvs.add(fv);
    	}
    	insert fvs;
    	
    	// insert one more, should fail
    	FilterValue__c fv = FilterValueTestUtility.buildFilterValue('newname', 'name', '=', 'blah', conf.id);
    	try {
    		insert fv;
    		// shouldn't get here
    		System.assert(false, 'exception should have been thrown!');
    	} catch(System.DmlException e) {
    		System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(0));
            System.assertEquals(Constants.tooManyFilterValuesErrorMessage, e.getDmlMessage(0));
    	}
    }
    
    static testMethod void testFieldValidations() {
        // set up a configuration
        Configuration__c conf = new Configuration__c();
        conf.name = 'testFieldValidations';
        conf.type__c = 'MUWTestObject__c';
        insert conf;
        
        // set fieldname to --none--
        FilterValue__c fv = FilterValueTestUtility.buildFilterValue('nofieldname', Constants.none, '=', 'blah', conf.id);
        try {
        	insert fv;
        	// shouldn't get here
        	System.assert(false, 'exception should have been thrown');
        } catch(System.DmlException e) {
        	System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(0));
            System.assertEquals(Constants.filterValueIncorrectFieldNameErrorMessage, e.getDmlMessage(0));
        }
        
        // set operator to --none--
        fv = FilterValueTestUtility.buildFilterValue('nooperatorname', 'name', Constants.none, 'blah', conf.id);
        try {
            insert fv;
            // shouldn't get here
            System.assert(false, 'exception should have been thrown');
        } catch(System.DmlException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(0));
            System.assertEquals(Constants.filterValueIncorrectOperatorErrorMessage, e.getDmlMessage(0));
        }
        
        // set logical join to something other than 'and' or 'or'
        fv = FilterValueTestUtility.buildFilterValue('dodo', 'name', '=', 'blah', 'NOTANDOROR', conf.id);
        try {
            insert fv;
            // shouldn't get here
            System.assert(false, 'exception should have been thrown');
        } catch(System.DmlException e) {
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(0));
            System.assertEquals(Constants.filterValueIncorrectLogicalJoinErrorMessage, e.getDmlMessage(0));
        }
    }

}